<?php


namespace api\resource;


class Aluno extends \api\models\Aluno
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}