<?php


namespace api\resource;


class Disciplina extends \api\models\Disciplina
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}