<?php


namespace api\resource;


class Encarregadoeducacao extends \api\models\Encarregadoeducacao
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}