<?php


namespace api\resource;


class Professor extends \api\models\Professor
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}