<?php


namespace api\resource;


class Teste extends \api\models\Teste
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}